/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * API version: 1.0.0
 * Contact: apisupport@mastercard.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package match

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
)

// Linger please
var (
	_ _context.Context
)

// AddTerminatedMerchantApiService AddTerminatedMerchantApi service
type AddTerminatedMerchantApiService service

type ApiAddMerchantPostRequest struct {
	ctx _context.Context
	ApiService *AddTerminatedMerchantApiService
	format *string
	addTerminatedMerchantRequestSchema *AddTerminatedMerchantRequestSchema
}

func (r ApiAddMerchantPostRequest) Format(format string) ApiAddMerchantPostRequest {
	r.format = &format
	return r
}
func (r ApiAddMerchantPostRequest) AddTerminatedMerchantRequestSchema(addTerminatedMerchantRequestSchema AddTerminatedMerchantRequestSchema) ApiAddMerchantPostRequest {
	r.addTerminatedMerchantRequestSchema = &addTerminatedMerchantRequestSchema
	return r
}

func (r ApiAddMerchantPostRequest) Execute() (AddTerminatedMerchantResponseSchema, *_nethttp.Response, error) {
	return r.ApiService.AddMerchantPostExecute(r)
}

/*
 * AddMerchantPost ##### Adds a new terminated merchant to MATCH system.
 * Used by Acquirers to add a terminated a merchant in the MATCH system. Merchant information, and up to five principal owners per merchant, can be provided by an acquiring bank as part of the listing. For adding a terminated merchant,  Acquirer Id and Merchant Id combination must be unique and Merchant Id should be less than 15 characters. For further details refer the documentation on [Use Cases.](/match/documentation/use-cases)

 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiAddMerchantPostRequest
 */
func (a *AddTerminatedMerchantApiService) AddMerchantPost(ctx _context.Context) ApiAddMerchantPostRequest {
	return ApiAddMerchantPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

/*
 * Execute executes the request
 * @return AddTerminatedMerchantResponseSchema
 */
func (a *AddTerminatedMerchantApiService) AddMerchantPostExecute(r ApiAddMerchantPostRequest) (AddTerminatedMerchantResponseSchema, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPost
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  AddTerminatedMerchantResponseSchema
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AddTerminatedMerchantApiService.AddMerchantPost")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/add-merchant"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.format == nil {
		return localVarReturnValue, nil, reportError("format is required and must be specified")
	}
	if r.addTerminatedMerchantRequestSchema == nil {
		return localVarReturnValue, nil, reportError("addTerminatedMerchantRequestSchema is required and must be specified")
	}

	localVarQueryParams.Add("Format", parameterToString(*r.format, ""))
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.addTerminatedMerchantRequestSchema
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ErrorsResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
