/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * API version: 1.0.0
 * Contact: apisupport@mastercard.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package match

import (
	"encoding/json"
)

// TerminationInquiryRequestSchema struct for TerminationInquiryRequestSchema
type TerminationInquiryRequestSchema struct {
	TerminationInquiryRequest *TerminationInquiryRequest `json:"TerminationInquiryRequest,omitempty"`
}

// NewTerminationInquiryRequestSchema instantiates a new TerminationInquiryRequestSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerminationInquiryRequestSchema() *TerminationInquiryRequestSchema {
	this := TerminationInquiryRequestSchema{}
	return &this
}

// NewTerminationInquiryRequestSchemaWithDefaults instantiates a new TerminationInquiryRequestSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerminationInquiryRequestSchemaWithDefaults() *TerminationInquiryRequestSchema {
	this := TerminationInquiryRequestSchema{}
	return &this
}

// GetTerminationInquiryRequest returns the TerminationInquiryRequest field value if set, zero value otherwise.
func (o *TerminationInquiryRequestSchema) GetTerminationInquiryRequest() TerminationInquiryRequest {
	if o == nil || o.TerminationInquiryRequest == nil {
		var ret TerminationInquiryRequest
		return ret
	}
	return *o.TerminationInquiryRequest
}

// GetTerminationInquiryRequestOk returns a tuple with the TerminationInquiryRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminationInquiryRequestSchema) GetTerminationInquiryRequestOk() (*TerminationInquiryRequest, bool) {
	if o == nil || o.TerminationInquiryRequest == nil {
		return nil, false
	}
	return o.TerminationInquiryRequest, true
}

// HasTerminationInquiryRequest returns a boolean if a field has been set.
func (o *TerminationInquiryRequestSchema) HasTerminationInquiryRequest() bool {
	if o != nil && o.TerminationInquiryRequest != nil {
		return true
	}

	return false
}

// SetTerminationInquiryRequest gets a reference to the given TerminationInquiryRequest and assigns it to the TerminationInquiryRequest field.
func (o *TerminationInquiryRequestSchema) SetTerminationInquiryRequest(v TerminationInquiryRequest) {
	o.TerminationInquiryRequest = &v
}

func (o TerminationInquiryRequestSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TerminationInquiryRequest != nil {
		toSerialize["TerminationInquiryRequest"] = o.TerminationInquiryRequest
	}
	return json.Marshal(toSerialize)
}

type NullableTerminationInquiryRequestSchema struct {
	value *TerminationInquiryRequestSchema
	isSet bool
}

func (v NullableTerminationInquiryRequestSchema) Get() *TerminationInquiryRequestSchema {
	return v.value
}

func (v *NullableTerminationInquiryRequestSchema) Set(val *TerminationInquiryRequestSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableTerminationInquiryRequestSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableTerminationInquiryRequestSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerminationInquiryRequestSchema(val *TerminationInquiryRequestSchema) *NullableTerminationInquiryRequestSchema {
	return &NullableTerminationInquiryRequestSchema{value: val, isSet: true}
}

func (v NullableTerminationInquiryRequestSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerminationInquiryRequestSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


