/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * API version: 1.0.0
 * Contact: apisupport@mastercard.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package match

import (
	"encoding/json"
)

// AddTerminatedMerchantRequestSchema struct for AddTerminatedMerchantRequestSchema
type AddTerminatedMerchantRequestSchema struct {
	AddMerchantRequest *AddMerchantRequest `json:"AddMerchantRequest,omitempty"`
}

// NewAddTerminatedMerchantRequestSchema instantiates a new AddTerminatedMerchantRequestSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddTerminatedMerchantRequestSchema() *AddTerminatedMerchantRequestSchema {
	this := AddTerminatedMerchantRequestSchema{}
	return &this
}

// NewAddTerminatedMerchantRequestSchemaWithDefaults instantiates a new AddTerminatedMerchantRequestSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddTerminatedMerchantRequestSchemaWithDefaults() *AddTerminatedMerchantRequestSchema {
	this := AddTerminatedMerchantRequestSchema{}
	return &this
}

// GetAddMerchantRequest returns the AddMerchantRequest field value if set, zero value otherwise.
func (o *AddTerminatedMerchantRequestSchema) GetAddMerchantRequest() AddMerchantRequest {
	if o == nil || o.AddMerchantRequest == nil {
		var ret AddMerchantRequest
		return ret
	}
	return *o.AddMerchantRequest
}

// GetAddMerchantRequestOk returns a tuple with the AddMerchantRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddTerminatedMerchantRequestSchema) GetAddMerchantRequestOk() (*AddMerchantRequest, bool) {
	if o == nil || o.AddMerchantRequest == nil {
		return nil, false
	}
	return o.AddMerchantRequest, true
}

// HasAddMerchantRequest returns a boolean if a field has been set.
func (o *AddTerminatedMerchantRequestSchema) HasAddMerchantRequest() bool {
	if o != nil && o.AddMerchantRequest != nil {
		return true
	}

	return false
}

// SetAddMerchantRequest gets a reference to the given AddMerchantRequest and assigns it to the AddMerchantRequest field.
func (o *AddTerminatedMerchantRequestSchema) SetAddMerchantRequest(v AddMerchantRequest) {
	o.AddMerchantRequest = &v
}

func (o AddTerminatedMerchantRequestSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AddMerchantRequest != nil {
		toSerialize["AddMerchantRequest"] = o.AddMerchantRequest
	}
	return json.Marshal(toSerialize)
}

type NullableAddTerminatedMerchantRequestSchema struct {
	value *AddTerminatedMerchantRequestSchema
	isSet bool
}

func (v NullableAddTerminatedMerchantRequestSchema) Get() *AddTerminatedMerchantRequestSchema {
	return v.value
}

func (v *NullableAddTerminatedMerchantRequestSchema) Set(val *AddTerminatedMerchantRequestSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableAddTerminatedMerchantRequestSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableAddTerminatedMerchantRequestSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddTerminatedMerchantRequestSchema(val *AddTerminatedMerchantRequestSchema) *NullableAddTerminatedMerchantRequestSchema {
	return &NullableAddTerminatedMerchantRequestSchema{value: val, isSet: true}
}

func (v NullableAddTerminatedMerchantRequestSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddTerminatedMerchantRequestSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


