/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * API version: 1.0.0
 * Contact: apisupport@mastercard.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package match

import (
	"encoding/json"
)

// Principal struct for Principal
type Principal struct {
	// The first name of the principal owner of the business.
	FirstName string `json:"FirstName"`
	// THe middle initial of the name of the principal owner of the business.
	MiddleInitial *string `json:"MiddleInitial,omitempty"`
	// The last name of the principal owner of the business.
	LastName string `json:"LastName"`
	Address *Address `json:"Address,omitempty"`
	// The Business or Merchant's phone number, including the area code. Within the USA, phone numbers have a length of 10, and for outside the US, it can be any length with a maximum of 12 digits. Within the U.S. phone numbers can not start with 0 or 1. If the number is outside the U.S. region; do not include the country code. The phone number must be digits only, with no format characters such as parenthesis or dashes.
	PhoneNumber *string `json:"PhoneNumber,omitempty"`
	// The Business or Merchant's alternate phone number, including the area code. Within the USA, phone numbers have a length of 10, and for out outside the US, a max length of 25. Within the U.S. phone numbers can not start with 0 or 1. If the number is outside the U.S. region; do not include the country code. The number must be digits only, with no format characters such as parenthesis or dashes.
	AltPhoneNumber *string `json:"AltPhoneNumber,omitempty"`
	// The Social Security number of a principal owner. If the principal owner is not from the U.S. Region, then use their national ID card number.
	NationalId *string `json:"NationalId,omitempty"`
	DriversLicense *DriversLicense `json:"DriversLicense,omitempty"`
}

// NewPrincipal instantiates a new Principal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrincipal(firstName string, lastName string) *Principal {
	this := Principal{}
	this.FirstName = firstName
	this.LastName = lastName
	return &this
}

// NewPrincipalWithDefaults instantiates a new Principal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrincipalWithDefaults() *Principal {
	this := Principal{}
	return &this
}

// GetFirstName returns the FirstName field value
func (o *Principal) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *Principal) GetFirstNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *Principal) SetFirstName(v string) {
	o.FirstName = v
}

// GetMiddleInitial returns the MiddleInitial field value if set, zero value otherwise.
func (o *Principal) GetMiddleInitial() string {
	if o == nil || o.MiddleInitial == nil {
		var ret string
		return ret
	}
	return *o.MiddleInitial
}

// GetMiddleInitialOk returns a tuple with the MiddleInitial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetMiddleInitialOk() (*string, bool) {
	if o == nil || o.MiddleInitial == nil {
		return nil, false
	}
	return o.MiddleInitial, true
}

// HasMiddleInitial returns a boolean if a field has been set.
func (o *Principal) HasMiddleInitial() bool {
	if o != nil && o.MiddleInitial != nil {
		return true
	}

	return false
}

// SetMiddleInitial gets a reference to the given string and assigns it to the MiddleInitial field.
func (o *Principal) SetMiddleInitial(v string) {
	o.MiddleInitial = &v
}

// GetLastName returns the LastName field value
func (o *Principal) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *Principal) GetLastNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *Principal) SetLastName(v string) {
	o.LastName = v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *Principal) GetAddress() Address {
	if o == nil || o.Address == nil {
		var ret Address
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetAddressOk() (*Address, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *Principal) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given Address and assigns it to the Address field.
func (o *Principal) SetAddress(v Address) {
	o.Address = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *Principal) GetPhoneNumber() string {
	if o == nil || o.PhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetPhoneNumberOk() (*string, bool) {
	if o == nil || o.PhoneNumber == nil {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *Principal) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber != nil {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *Principal) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetAltPhoneNumber returns the AltPhoneNumber field value if set, zero value otherwise.
func (o *Principal) GetAltPhoneNumber() string {
	if o == nil || o.AltPhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.AltPhoneNumber
}

// GetAltPhoneNumberOk returns a tuple with the AltPhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetAltPhoneNumberOk() (*string, bool) {
	if o == nil || o.AltPhoneNumber == nil {
		return nil, false
	}
	return o.AltPhoneNumber, true
}

// HasAltPhoneNumber returns a boolean if a field has been set.
func (o *Principal) HasAltPhoneNumber() bool {
	if o != nil && o.AltPhoneNumber != nil {
		return true
	}

	return false
}

// SetAltPhoneNumber gets a reference to the given string and assigns it to the AltPhoneNumber field.
func (o *Principal) SetAltPhoneNumber(v string) {
	o.AltPhoneNumber = &v
}

// GetNationalId returns the NationalId field value if set, zero value otherwise.
func (o *Principal) GetNationalId() string {
	if o == nil || o.NationalId == nil {
		var ret string
		return ret
	}
	return *o.NationalId
}

// GetNationalIdOk returns a tuple with the NationalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetNationalIdOk() (*string, bool) {
	if o == nil || o.NationalId == nil {
		return nil, false
	}
	return o.NationalId, true
}

// HasNationalId returns a boolean if a field has been set.
func (o *Principal) HasNationalId() bool {
	if o != nil && o.NationalId != nil {
		return true
	}

	return false
}

// SetNationalId gets a reference to the given string and assigns it to the NationalId field.
func (o *Principal) SetNationalId(v string) {
	o.NationalId = &v
}

// GetDriversLicense returns the DriversLicense field value if set, zero value otherwise.
func (o *Principal) GetDriversLicense() DriversLicense {
	if o == nil || o.DriversLicense == nil {
		var ret DriversLicense
		return ret
	}
	return *o.DriversLicense
}

// GetDriversLicenseOk returns a tuple with the DriversLicense field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Principal) GetDriversLicenseOk() (*DriversLicense, bool) {
	if o == nil || o.DriversLicense == nil {
		return nil, false
	}
	return o.DriversLicense, true
}

// HasDriversLicense returns a boolean if a field has been set.
func (o *Principal) HasDriversLicense() bool {
	if o != nil && o.DriversLicense != nil {
		return true
	}

	return false
}

// SetDriversLicense gets a reference to the given DriversLicense and assigns it to the DriversLicense field.
func (o *Principal) SetDriversLicense(v DriversLicense) {
	o.DriversLicense = &v
}

func (o Principal) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["FirstName"] = o.FirstName
	}
	if o.MiddleInitial != nil {
		toSerialize["MiddleInitial"] = o.MiddleInitial
	}
	if true {
		toSerialize["LastName"] = o.LastName
	}
	if o.Address != nil {
		toSerialize["Address"] = o.Address
	}
	if o.PhoneNumber != nil {
		toSerialize["PhoneNumber"] = o.PhoneNumber
	}
	if o.AltPhoneNumber != nil {
		toSerialize["AltPhoneNumber"] = o.AltPhoneNumber
	}
	if o.NationalId != nil {
		toSerialize["NationalId"] = o.NationalId
	}
	if o.DriversLicense != nil {
		toSerialize["DriversLicense"] = o.DriversLicense
	}
	return json.Marshal(toSerialize)
}

type NullablePrincipal struct {
	value *Principal
	isSet bool
}

func (v NullablePrincipal) Get() *Principal {
	return v.value
}

func (v *NullablePrincipal) Set(val *Principal) {
	v.value = val
	v.isSet = true
}

func (v NullablePrincipal) IsSet() bool {
	return v.isSet
}

func (v *NullablePrincipal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrincipal(val *Principal) *NullablePrincipal {
	return &NullablePrincipal{value: val, isSet: true}
}

func (v NullablePrincipal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrincipal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


