/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * API version: 1.0.0
 * Contact: apisupport@mastercard.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package match

import (
	"encoding/json"
)

// InquiredMerchantMerchant struct for InquiredMerchantMerchant
type InquiredMerchantMerchant struct {
	// The name of the Business which has been terminated.
	Name *string `json:"Name,omitempty"`
	// The name used by a merchant that could be different from the legal name of the business. Such as Bait R Us instead of the legal name, The Bait Shop
	DoingBusinessAsName *string `json:"DoingBusinessAsName,omitempty"`
	// The Member ICA that has added the merchant to the MATCH system
	AddedByAcquirerID *string `json:"AddedByAcquirerID,omitempty"`
	// The date on which the merchant was added to the MATCH system. Format MM/DD/YYYY
	AddedOnDate *string `json:"AddedOnDate,omitempty"`
	// The Business or Merchant's phone number.
	PhoneNumber *string `json:"PhoneNumber,omitempty"`
	// The Business or Merchant's alternate phone number.
	AltPhoneNumber *string `json:"AltPhoneNumber,omitempty"`
	Address *Address `json:"Address,omitempty"`
	// The Merchant's state tax ID; for the U.S region only. Return value will be hidden.
	CountrySubdivisionTaxId *string `json:"CountrySubdivisionTaxId,omitempty"`
	// The National tax ID or business registration number. Return value will be hidden.
	NationalTaxId *string `json:"NationalTaxId,omitempty"`
	// The name of the service provider associated with the merchant listed in the MATCH.
	ServiceProvLegal *string `json:"ServiceProvLegal,omitempty"`
	// The name of the service provider associated with the merchant listed in the MATCH.
	ServiceProvDBA *string `json:"ServiceProvDBA,omitempty"`
	// A two digit numeric code indication why a particular merchant was terminated.  01   Account Data Compromise, 02   Common Points of Purchase, 03   Laundering, 04   Excessive Chargebacks, 05   Excessive Fraud, 06   Reserved for Future Use, 07   Fraud Conviction, 08   MasterCard Questionable Merchant Audit Program, 09   Bankruptcy/Liquidation/Insolvency, 10   Violation of MasterCard Standards, 11   Merchant collusion, 12   PCI Data Security Standard, Noncompliance, 13   Illegal Transactions, 14   Identity Theft
	TerminationReasonCode *string `json:"TerminationReasonCode,omitempty"`
	UrlGroup *[]UrlGroup `json:"UrlGroup,omitempty"`
	Url *[]Url `json:"Url,omitempty"`
	Principal *[]Principal `json:"Principal,omitempty"`
	SearchCriteria *SearchCriteria `json:"SearchCriteria,omitempty"`
	MerchantMatch *MerchantMatch `json:"MerchantMatch,omitempty"`
}

// NewInquiredMerchantMerchant instantiates a new InquiredMerchantMerchant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInquiredMerchantMerchant() *InquiredMerchantMerchant {
	this := InquiredMerchantMerchant{}
	return &this
}

// NewInquiredMerchantMerchantWithDefaults instantiates a new InquiredMerchantMerchant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInquiredMerchantMerchantWithDefaults() *InquiredMerchantMerchant {
	this := InquiredMerchantMerchant{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InquiredMerchantMerchant) SetName(v string) {
	o.Name = &v
}

// GetDoingBusinessAsName returns the DoingBusinessAsName field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetDoingBusinessAsName() string {
	if o == nil || o.DoingBusinessAsName == nil {
		var ret string
		return ret
	}
	return *o.DoingBusinessAsName
}

// GetDoingBusinessAsNameOk returns a tuple with the DoingBusinessAsName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetDoingBusinessAsNameOk() (*string, bool) {
	if o == nil || o.DoingBusinessAsName == nil {
		return nil, false
	}
	return o.DoingBusinessAsName, true
}

// HasDoingBusinessAsName returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasDoingBusinessAsName() bool {
	if o != nil && o.DoingBusinessAsName != nil {
		return true
	}

	return false
}

// SetDoingBusinessAsName gets a reference to the given string and assigns it to the DoingBusinessAsName field.
func (o *InquiredMerchantMerchant) SetDoingBusinessAsName(v string) {
	o.DoingBusinessAsName = &v
}

// GetAddedByAcquirerID returns the AddedByAcquirerID field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetAddedByAcquirerID() string {
	if o == nil || o.AddedByAcquirerID == nil {
		var ret string
		return ret
	}
	return *o.AddedByAcquirerID
}

// GetAddedByAcquirerIDOk returns a tuple with the AddedByAcquirerID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetAddedByAcquirerIDOk() (*string, bool) {
	if o == nil || o.AddedByAcquirerID == nil {
		return nil, false
	}
	return o.AddedByAcquirerID, true
}

// HasAddedByAcquirerID returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasAddedByAcquirerID() bool {
	if o != nil && o.AddedByAcquirerID != nil {
		return true
	}

	return false
}

// SetAddedByAcquirerID gets a reference to the given string and assigns it to the AddedByAcquirerID field.
func (o *InquiredMerchantMerchant) SetAddedByAcquirerID(v string) {
	o.AddedByAcquirerID = &v
}

// GetAddedOnDate returns the AddedOnDate field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetAddedOnDate() string {
	if o == nil || o.AddedOnDate == nil {
		var ret string
		return ret
	}
	return *o.AddedOnDate
}

// GetAddedOnDateOk returns a tuple with the AddedOnDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetAddedOnDateOk() (*string, bool) {
	if o == nil || o.AddedOnDate == nil {
		return nil, false
	}
	return o.AddedOnDate, true
}

// HasAddedOnDate returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasAddedOnDate() bool {
	if o != nil && o.AddedOnDate != nil {
		return true
	}

	return false
}

// SetAddedOnDate gets a reference to the given string and assigns it to the AddedOnDate field.
func (o *InquiredMerchantMerchant) SetAddedOnDate(v string) {
	o.AddedOnDate = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetPhoneNumber() string {
	if o == nil || o.PhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetPhoneNumberOk() (*string, bool) {
	if o == nil || o.PhoneNumber == nil {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber != nil {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *InquiredMerchantMerchant) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetAltPhoneNumber returns the AltPhoneNumber field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetAltPhoneNumber() string {
	if o == nil || o.AltPhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.AltPhoneNumber
}

// GetAltPhoneNumberOk returns a tuple with the AltPhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetAltPhoneNumberOk() (*string, bool) {
	if o == nil || o.AltPhoneNumber == nil {
		return nil, false
	}
	return o.AltPhoneNumber, true
}

// HasAltPhoneNumber returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasAltPhoneNumber() bool {
	if o != nil && o.AltPhoneNumber != nil {
		return true
	}

	return false
}

// SetAltPhoneNumber gets a reference to the given string and assigns it to the AltPhoneNumber field.
func (o *InquiredMerchantMerchant) SetAltPhoneNumber(v string) {
	o.AltPhoneNumber = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetAddress() Address {
	if o == nil || o.Address == nil {
		var ret Address
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetAddressOk() (*Address, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given Address and assigns it to the Address field.
func (o *InquiredMerchantMerchant) SetAddress(v Address) {
	o.Address = &v
}

// GetCountrySubdivisionTaxId returns the CountrySubdivisionTaxId field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetCountrySubdivisionTaxId() string {
	if o == nil || o.CountrySubdivisionTaxId == nil {
		var ret string
		return ret
	}
	return *o.CountrySubdivisionTaxId
}

// GetCountrySubdivisionTaxIdOk returns a tuple with the CountrySubdivisionTaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetCountrySubdivisionTaxIdOk() (*string, bool) {
	if o == nil || o.CountrySubdivisionTaxId == nil {
		return nil, false
	}
	return o.CountrySubdivisionTaxId, true
}

// HasCountrySubdivisionTaxId returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasCountrySubdivisionTaxId() bool {
	if o != nil && o.CountrySubdivisionTaxId != nil {
		return true
	}

	return false
}

// SetCountrySubdivisionTaxId gets a reference to the given string and assigns it to the CountrySubdivisionTaxId field.
func (o *InquiredMerchantMerchant) SetCountrySubdivisionTaxId(v string) {
	o.CountrySubdivisionTaxId = &v
}

// GetNationalTaxId returns the NationalTaxId field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetNationalTaxId() string {
	if o == nil || o.NationalTaxId == nil {
		var ret string
		return ret
	}
	return *o.NationalTaxId
}

// GetNationalTaxIdOk returns a tuple with the NationalTaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetNationalTaxIdOk() (*string, bool) {
	if o == nil || o.NationalTaxId == nil {
		return nil, false
	}
	return o.NationalTaxId, true
}

// HasNationalTaxId returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasNationalTaxId() bool {
	if o != nil && o.NationalTaxId != nil {
		return true
	}

	return false
}

// SetNationalTaxId gets a reference to the given string and assigns it to the NationalTaxId field.
func (o *InquiredMerchantMerchant) SetNationalTaxId(v string) {
	o.NationalTaxId = &v
}

// GetServiceProvLegal returns the ServiceProvLegal field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetServiceProvLegal() string {
	if o == nil || o.ServiceProvLegal == nil {
		var ret string
		return ret
	}
	return *o.ServiceProvLegal
}

// GetServiceProvLegalOk returns a tuple with the ServiceProvLegal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetServiceProvLegalOk() (*string, bool) {
	if o == nil || o.ServiceProvLegal == nil {
		return nil, false
	}
	return o.ServiceProvLegal, true
}

// HasServiceProvLegal returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasServiceProvLegal() bool {
	if o != nil && o.ServiceProvLegal != nil {
		return true
	}

	return false
}

// SetServiceProvLegal gets a reference to the given string and assigns it to the ServiceProvLegal field.
func (o *InquiredMerchantMerchant) SetServiceProvLegal(v string) {
	o.ServiceProvLegal = &v
}

// GetServiceProvDBA returns the ServiceProvDBA field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetServiceProvDBA() string {
	if o == nil || o.ServiceProvDBA == nil {
		var ret string
		return ret
	}
	return *o.ServiceProvDBA
}

// GetServiceProvDBAOk returns a tuple with the ServiceProvDBA field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetServiceProvDBAOk() (*string, bool) {
	if o == nil || o.ServiceProvDBA == nil {
		return nil, false
	}
	return o.ServiceProvDBA, true
}

// HasServiceProvDBA returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasServiceProvDBA() bool {
	if o != nil && o.ServiceProvDBA != nil {
		return true
	}

	return false
}

// SetServiceProvDBA gets a reference to the given string and assigns it to the ServiceProvDBA field.
func (o *InquiredMerchantMerchant) SetServiceProvDBA(v string) {
	o.ServiceProvDBA = &v
}

// GetTerminationReasonCode returns the TerminationReasonCode field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetTerminationReasonCode() string {
	if o == nil || o.TerminationReasonCode == nil {
		var ret string
		return ret
	}
	return *o.TerminationReasonCode
}

// GetTerminationReasonCodeOk returns a tuple with the TerminationReasonCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetTerminationReasonCodeOk() (*string, bool) {
	if o == nil || o.TerminationReasonCode == nil {
		return nil, false
	}
	return o.TerminationReasonCode, true
}

// HasTerminationReasonCode returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasTerminationReasonCode() bool {
	if o != nil && o.TerminationReasonCode != nil {
		return true
	}

	return false
}

// SetTerminationReasonCode gets a reference to the given string and assigns it to the TerminationReasonCode field.
func (o *InquiredMerchantMerchant) SetTerminationReasonCode(v string) {
	o.TerminationReasonCode = &v
}

// GetUrlGroup returns the UrlGroup field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetUrlGroup() []UrlGroup {
	if o == nil || o.UrlGroup == nil {
		var ret []UrlGroup
		return ret
	}
	return *o.UrlGroup
}

// GetUrlGroupOk returns a tuple with the UrlGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetUrlGroupOk() (*[]UrlGroup, bool) {
	if o == nil || o.UrlGroup == nil {
		return nil, false
	}
	return o.UrlGroup, true
}

// HasUrlGroup returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasUrlGroup() bool {
	if o != nil && o.UrlGroup != nil {
		return true
	}

	return false
}

// SetUrlGroup gets a reference to the given []UrlGroup and assigns it to the UrlGroup field.
func (o *InquiredMerchantMerchant) SetUrlGroup(v []UrlGroup) {
	o.UrlGroup = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetUrl() []Url {
	if o == nil || o.Url == nil {
		var ret []Url
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetUrlOk() (*[]Url, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given []Url and assigns it to the Url field.
func (o *InquiredMerchantMerchant) SetUrl(v []Url) {
	o.Url = &v
}

// GetPrincipal returns the Principal field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetPrincipal() []Principal {
	if o == nil || o.Principal == nil {
		var ret []Principal
		return ret
	}
	return *o.Principal
}

// GetPrincipalOk returns a tuple with the Principal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetPrincipalOk() (*[]Principal, bool) {
	if o == nil || o.Principal == nil {
		return nil, false
	}
	return o.Principal, true
}

// HasPrincipal returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasPrincipal() bool {
	if o != nil && o.Principal != nil {
		return true
	}

	return false
}

// SetPrincipal gets a reference to the given []Principal and assigns it to the Principal field.
func (o *InquiredMerchantMerchant) SetPrincipal(v []Principal) {
	o.Principal = &v
}

// GetSearchCriteria returns the SearchCriteria field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetSearchCriteria() SearchCriteria {
	if o == nil || o.SearchCriteria == nil {
		var ret SearchCriteria
		return ret
	}
	return *o.SearchCriteria
}

// GetSearchCriteriaOk returns a tuple with the SearchCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetSearchCriteriaOk() (*SearchCriteria, bool) {
	if o == nil || o.SearchCriteria == nil {
		return nil, false
	}
	return o.SearchCriteria, true
}

// HasSearchCriteria returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasSearchCriteria() bool {
	if o != nil && o.SearchCriteria != nil {
		return true
	}

	return false
}

// SetSearchCriteria gets a reference to the given SearchCriteria and assigns it to the SearchCriteria field.
func (o *InquiredMerchantMerchant) SetSearchCriteria(v SearchCriteria) {
	o.SearchCriteria = &v
}

// GetMerchantMatch returns the MerchantMatch field value if set, zero value otherwise.
func (o *InquiredMerchantMerchant) GetMerchantMatch() MerchantMatch {
	if o == nil || o.MerchantMatch == nil {
		var ret MerchantMatch
		return ret
	}
	return *o.MerchantMatch
}

// GetMerchantMatchOk returns a tuple with the MerchantMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InquiredMerchantMerchant) GetMerchantMatchOk() (*MerchantMatch, bool) {
	if o == nil || o.MerchantMatch == nil {
		return nil, false
	}
	return o.MerchantMatch, true
}

// HasMerchantMatch returns a boolean if a field has been set.
func (o *InquiredMerchantMerchant) HasMerchantMatch() bool {
	if o != nil && o.MerchantMatch != nil {
		return true
	}

	return false
}

// SetMerchantMatch gets a reference to the given MerchantMatch and assigns it to the MerchantMatch field.
func (o *InquiredMerchantMerchant) SetMerchantMatch(v MerchantMatch) {
	o.MerchantMatch = &v
}

func (o InquiredMerchantMerchant) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["Name"] = o.Name
	}
	if o.DoingBusinessAsName != nil {
		toSerialize["DoingBusinessAsName"] = o.DoingBusinessAsName
	}
	if o.AddedByAcquirerID != nil {
		toSerialize["AddedByAcquirerID"] = o.AddedByAcquirerID
	}
	if o.AddedOnDate != nil {
		toSerialize["AddedOnDate"] = o.AddedOnDate
	}
	if o.PhoneNumber != nil {
		toSerialize["PhoneNumber"] = o.PhoneNumber
	}
	if o.AltPhoneNumber != nil {
		toSerialize["AltPhoneNumber"] = o.AltPhoneNumber
	}
	if o.Address != nil {
		toSerialize["Address"] = o.Address
	}
	if o.CountrySubdivisionTaxId != nil {
		toSerialize["CountrySubdivisionTaxId"] = o.CountrySubdivisionTaxId
	}
	if o.NationalTaxId != nil {
		toSerialize["NationalTaxId"] = o.NationalTaxId
	}
	if o.ServiceProvLegal != nil {
		toSerialize["ServiceProvLegal"] = o.ServiceProvLegal
	}
	if o.ServiceProvDBA != nil {
		toSerialize["ServiceProvDBA"] = o.ServiceProvDBA
	}
	if o.TerminationReasonCode != nil {
		toSerialize["TerminationReasonCode"] = o.TerminationReasonCode
	}
	if o.UrlGroup != nil {
		toSerialize["UrlGroup"] = o.UrlGroup
	}
	if o.Url != nil {
		toSerialize["Url"] = o.Url
	}
	if o.Principal != nil {
		toSerialize["Principal"] = o.Principal
	}
	if o.SearchCriteria != nil {
		toSerialize["SearchCriteria"] = o.SearchCriteria
	}
	if o.MerchantMatch != nil {
		toSerialize["MerchantMatch"] = o.MerchantMatch
	}
	return json.Marshal(toSerialize)
}

type NullableInquiredMerchantMerchant struct {
	value *InquiredMerchantMerchant
	isSet bool
}

func (v NullableInquiredMerchantMerchant) Get() *InquiredMerchantMerchant {
	return v.value
}

func (v *NullableInquiredMerchantMerchant) Set(val *InquiredMerchantMerchant) {
	v.value = val
	v.isSet = true
}

func (v NullableInquiredMerchantMerchant) IsSet() bool {
	return v.isSet
}

func (v *NullableInquiredMerchantMerchant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInquiredMerchantMerchant(val *InquiredMerchantMerchant) *NullableInquiredMerchantMerchant {
	return &NullableInquiredMerchantMerchant{value: val, isSet: true}
}

func (v NullableInquiredMerchantMerchant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInquiredMerchantMerchant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


