/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * API version: 1.0.0
 * Contact: apisupport@mastercard.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package match

import (
	"encoding/json"
)

// AddTerminatedMerchantResponseSchema struct for AddTerminatedMerchantResponseSchema
type AddTerminatedMerchantResponseSchema struct {
	AddMerchantResponse *AddMerchantResponse `json:"AddMerchantResponse,omitempty"`
}

// NewAddTerminatedMerchantResponseSchema instantiates a new AddTerminatedMerchantResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddTerminatedMerchantResponseSchema() *AddTerminatedMerchantResponseSchema {
	this := AddTerminatedMerchantResponseSchema{}
	return &this
}

// NewAddTerminatedMerchantResponseSchemaWithDefaults instantiates a new AddTerminatedMerchantResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddTerminatedMerchantResponseSchemaWithDefaults() *AddTerminatedMerchantResponseSchema {
	this := AddTerminatedMerchantResponseSchema{}
	return &this
}

// GetAddMerchantResponse returns the AddMerchantResponse field value if set, zero value otherwise.
func (o *AddTerminatedMerchantResponseSchema) GetAddMerchantResponse() AddMerchantResponse {
	if o == nil || o.AddMerchantResponse == nil {
		var ret AddMerchantResponse
		return ret
	}
	return *o.AddMerchantResponse
}

// GetAddMerchantResponseOk returns a tuple with the AddMerchantResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddTerminatedMerchantResponseSchema) GetAddMerchantResponseOk() (*AddMerchantResponse, bool) {
	if o == nil || o.AddMerchantResponse == nil {
		return nil, false
	}
	return o.AddMerchantResponse, true
}

// HasAddMerchantResponse returns a boolean if a field has been set.
func (o *AddTerminatedMerchantResponseSchema) HasAddMerchantResponse() bool {
	if o != nil && o.AddMerchantResponse != nil {
		return true
	}

	return false
}

// SetAddMerchantResponse gets a reference to the given AddMerchantResponse and assigns it to the AddMerchantResponse field.
func (o *AddTerminatedMerchantResponseSchema) SetAddMerchantResponse(v AddMerchantResponse) {
	o.AddMerchantResponse = &v
}

func (o AddTerminatedMerchantResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AddMerchantResponse != nil {
		toSerialize["AddMerchantResponse"] = o.AddMerchantResponse
	}
	return json.Marshal(toSerialize)
}

type NullableAddTerminatedMerchantResponseSchema struct {
	value *AddTerminatedMerchantResponseSchema
	isSet bool
}

func (v NullableAddTerminatedMerchantResponseSchema) Get() *AddTerminatedMerchantResponseSchema {
	return v.value
}

func (v *NullableAddTerminatedMerchantResponseSchema) Set(val *AddTerminatedMerchantResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableAddTerminatedMerchantResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableAddTerminatedMerchantResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddTerminatedMerchantResponseSchema(val *AddTerminatedMerchantResponseSchema) *NullableAddTerminatedMerchantResponseSchema {
	return &NullableAddTerminatedMerchantResponseSchema{value: val, isSet: true}
}

func (v NullableAddTerminatedMerchantResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddTerminatedMerchantResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


