/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * API version: 1.0.0
 * Contact: apisupport@mastercard.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package match

import (
	"encoding/json"
)

// RetroInquiryResponseSchema struct for RetroInquiryResponseSchema
type RetroInquiryResponseSchema struct {
	RetroInquiryResponse *RetroInquiryResponse `json:"RetroInquiryResponse,omitempty"`
}

// NewRetroInquiryResponseSchema instantiates a new RetroInquiryResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetroInquiryResponseSchema() *RetroInquiryResponseSchema {
	this := RetroInquiryResponseSchema{}
	return &this
}

// NewRetroInquiryResponseSchemaWithDefaults instantiates a new RetroInquiryResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetroInquiryResponseSchemaWithDefaults() *RetroInquiryResponseSchema {
	this := RetroInquiryResponseSchema{}
	return &this
}

// GetRetroInquiryResponse returns the RetroInquiryResponse field value if set, zero value otherwise.
func (o *RetroInquiryResponseSchema) GetRetroInquiryResponse() RetroInquiryResponse {
	if o == nil || o.RetroInquiryResponse == nil {
		var ret RetroInquiryResponse
		return ret
	}
	return *o.RetroInquiryResponse
}

// GetRetroInquiryResponseOk returns a tuple with the RetroInquiryResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetroInquiryResponseSchema) GetRetroInquiryResponseOk() (*RetroInquiryResponse, bool) {
	if o == nil || o.RetroInquiryResponse == nil {
		return nil, false
	}
	return o.RetroInquiryResponse, true
}

// HasRetroInquiryResponse returns a boolean if a field has been set.
func (o *RetroInquiryResponseSchema) HasRetroInquiryResponse() bool {
	if o != nil && o.RetroInquiryResponse != nil {
		return true
	}

	return false
}

// SetRetroInquiryResponse gets a reference to the given RetroInquiryResponse and assigns it to the RetroInquiryResponse field.
func (o *RetroInquiryResponseSchema) SetRetroInquiryResponse(v RetroInquiryResponse) {
	o.RetroInquiryResponse = &v
}

func (o RetroInquiryResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RetroInquiryResponse != nil {
		toSerialize["RetroInquiryResponse"] = o.RetroInquiryResponse
	}
	return json.Marshal(toSerialize)
}

type NullableRetroInquiryResponseSchema struct {
	value *RetroInquiryResponseSchema
	isSet bool
}

func (v NullableRetroInquiryResponseSchema) Get() *RetroInquiryResponseSchema {
	return v.value
}

func (v *NullableRetroInquiryResponseSchema) Set(val *RetroInquiryResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableRetroInquiryResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableRetroInquiryResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetroInquiryResponseSchema(val *RetroInquiryResponseSchema) *NullableRetroInquiryResponseSchema {
	return &NullableRetroInquiryResponseSchema{value: val, isSet: true}
}

func (v NullableRetroInquiryResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetroInquiryResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


