/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * API version: 1.0.0
 * Contact: apisupport@mastercard.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package match

import (
	"encoding/json"
)

// RetroInquiryRequest struct for RetroInquiryRequest
type RetroInquiryRequest struct {
	// This is the reference number that was obtained from Retroactive Inquiry Summary resource.
	InquiryReferenceNumber *string `json:"InquiryReferenceNumber,omitempty"`
}

// NewRetroInquiryRequest instantiates a new RetroInquiryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetroInquiryRequest() *RetroInquiryRequest {
	this := RetroInquiryRequest{}
	return &this
}

// NewRetroInquiryRequestWithDefaults instantiates a new RetroInquiryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetroInquiryRequestWithDefaults() *RetroInquiryRequest {
	this := RetroInquiryRequest{}
	return &this
}

// GetInquiryReferenceNumber returns the InquiryReferenceNumber field value if set, zero value otherwise.
func (o *RetroInquiryRequest) GetInquiryReferenceNumber() string {
	if o == nil || o.InquiryReferenceNumber == nil {
		var ret string
		return ret
	}
	return *o.InquiryReferenceNumber
}

// GetInquiryReferenceNumberOk returns a tuple with the InquiryReferenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetroInquiryRequest) GetInquiryReferenceNumberOk() (*string, bool) {
	if o == nil || o.InquiryReferenceNumber == nil {
		return nil, false
	}
	return o.InquiryReferenceNumber, true
}

// HasInquiryReferenceNumber returns a boolean if a field has been set.
func (o *RetroInquiryRequest) HasInquiryReferenceNumber() bool {
	if o != nil && o.InquiryReferenceNumber != nil {
		return true
	}

	return false
}

// SetInquiryReferenceNumber gets a reference to the given string and assigns it to the InquiryReferenceNumber field.
func (o *RetroInquiryRequest) SetInquiryReferenceNumber(v string) {
	o.InquiryReferenceNumber = &v
}

func (o RetroInquiryRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.InquiryReferenceNumber != nil {
		toSerialize["InquiryReferenceNumber"] = o.InquiryReferenceNumber
	}
	return json.Marshal(toSerialize)
}

type NullableRetroInquiryRequest struct {
	value *RetroInquiryRequest
	isSet bool
}

func (v NullableRetroInquiryRequest) Get() *RetroInquiryRequest {
	return v.value
}

func (v *NullableRetroInquiryRequest) Set(val *RetroInquiryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRetroInquiryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRetroInquiryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetroInquiryRequest(val *RetroInquiryRequest) *NullableRetroInquiryRequest {
	return &NullableRetroInquiryRequest{value: val, isSet: true}
}

func (v NullableRetroInquiryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetroInquiryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


