/*
 * MATCH API
 *
 * Helps acquirers identify potentially high-risk merchants before entering to a merchant agreement.
 *
 * API version: 1.0.0
 * Contact: apisupport@mastercard.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package match

import (
	"encoding/json"
)

// RetroInquiryRequestSchema struct for RetroInquiryRequestSchema
type RetroInquiryRequestSchema struct {
	RetroInquiryRequest *RetroInquiryRequest `json:"RetroInquiryRequest,omitempty"`
}

// NewRetroInquiryRequestSchema instantiates a new RetroInquiryRequestSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetroInquiryRequestSchema() *RetroInquiryRequestSchema {
	this := RetroInquiryRequestSchema{}
	return &this
}

// NewRetroInquiryRequestSchemaWithDefaults instantiates a new RetroInquiryRequestSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetroInquiryRequestSchemaWithDefaults() *RetroInquiryRequestSchema {
	this := RetroInquiryRequestSchema{}
	return &this
}

// GetRetroInquiryRequest returns the RetroInquiryRequest field value if set, zero value otherwise.
func (o *RetroInquiryRequestSchema) GetRetroInquiryRequest() RetroInquiryRequest {
	if o == nil || o.RetroInquiryRequest == nil {
		var ret RetroInquiryRequest
		return ret
	}
	return *o.RetroInquiryRequest
}

// GetRetroInquiryRequestOk returns a tuple with the RetroInquiryRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RetroInquiryRequestSchema) GetRetroInquiryRequestOk() (*RetroInquiryRequest, bool) {
	if o == nil || o.RetroInquiryRequest == nil {
		return nil, false
	}
	return o.RetroInquiryRequest, true
}

// HasRetroInquiryRequest returns a boolean if a field has been set.
func (o *RetroInquiryRequestSchema) HasRetroInquiryRequest() bool {
	if o != nil && o.RetroInquiryRequest != nil {
		return true
	}

	return false
}

// SetRetroInquiryRequest gets a reference to the given RetroInquiryRequest and assigns it to the RetroInquiryRequest field.
func (o *RetroInquiryRequestSchema) SetRetroInquiryRequest(v RetroInquiryRequest) {
	o.RetroInquiryRequest = &v
}

func (o RetroInquiryRequestSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RetroInquiryRequest != nil {
		toSerialize["RetroInquiryRequest"] = o.RetroInquiryRequest
	}
	return json.Marshal(toSerialize)
}

type NullableRetroInquiryRequestSchema struct {
	value *RetroInquiryRequestSchema
	isSet bool
}

func (v NullableRetroInquiryRequestSchema) Get() *RetroInquiryRequestSchema {
	return v.value
}

func (v *NullableRetroInquiryRequestSchema) Set(val *RetroInquiryRequestSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableRetroInquiryRequestSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableRetroInquiryRequestSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetroInquiryRequestSchema(val *RetroInquiryRequestSchema) *NullableRetroInquiryRequestSchema {
	return &NullableRetroInquiryRequestSchema{value: val, isSet: true}
}

func (v NullableRetroInquiryRequestSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetroInquiryRequestSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


